name: 'Gitea List Pull Requests'
description: 'Gitea Action that lists pull requests with filtering conditions'
author: 'You-Sheng Yang'
branding:
  icon: 'list'
  color: 'blue'

inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: >
      Access Token used to retrieve pull requests from the specified the
      repository.

      [Learn more about generating and using access
      tokens.](https://docs.gitea.com/development/api-usage)
    default: ${{ github.token }}
  server_url:
    description: >
      The server URL for the Gitea instance that you are trying to enumerate
      pull requests from, will use environment defaults from the same instance
      that the workflow is running from unless specified. Example URL is
      https://gitea.com.
    default: ${{ github.server_url }}

outputs:
  json:
    description: Array of pull requests object in JSON format.

runs:
  using: node20
  main: dist/index.js
