name: 'Gitea List Pull Requests'
description: 'Gitea Action that lists pull requests with filtering conditions'
author: 'You-Sheng Yang'
branding:
  icon: 'list'
  color: 'blue'

inputs:
  repository:
    description: >
      Repository name with owner. For example, vicamo/gitea-list-pull-requests
    default: ${{ github.repository }}
  token:
    description: >
      Access Token used to retrieve pull requests from the specified the
      repository.

      [Learn more about generating and using access
      tokens.](https://docs.gitea.com/development/api-usage)
    default: ${{ github.token }}
  server_url:
    description: >
      The server URL for the Gitea instance that you are trying to enumerate
      pull requests from, will use environment defaults from the same instance
      that the workflow is running from unless specified. Example URL is
      https://gitea.com.
    default: ${{ github.server_url }}
  state:
    description: >
      State of pull request, e.g. open, closed, or all.
    default: 'all'
  milestone:
    description: >
      A project milestone name. If the specified milestone is not available for
      the specified project, it will return an error.
  labels:
    description: >
      A multi-line string with one label name for each line. If any of the
      specified label is not available for the specified project, it will return
      an error.

outputs:
  json:
    description: Array of pull requests object in JSON format.

runs:
  using: node20
  main: dist/index.js
