name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - limit: 1
            state: 'open'
          - limit: 1
            milestone: 'v0.10.0'
            labels: 'kind/feature'
          - limit: 1
            labels: |
              kind/bug
              kind/docs

              kind/enhancement
          - page: 2
            limit: 2

    steps:
      - name: Am I on Gitea?
        id: identity
        run: |
          echo "is_gitea=${{ contains(github.server_url, 'gitea') && 'true' || 'false' }}" | \
              tee -a "${GITHUB_OUTPUT}"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          server_url: http://gitea.com
          token:
            ${{ steps.identity.outputs.is_gitea == 'true' && github.token || ''
            }}
          repository: 'gitea/tea'
          state: ${{ matrix.state || 'all' }}
          milestone: ${{ matrix.milestone }}
          labels: ${{ matrix.labels }}
          page: ${{ matrix.page }}
          limit: ${{ matrix.limit }}

      - name: Print Output
        id: output
        run: |
          cat <<EOF
          ${{ steps.test-action.outputs.json }}
          EOF
